{
  "stats": {
    "suites": 1,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2021-04-19T21:25:22.507Z",
    "end": "2021-04-19T21:25:26.008Z",
    "duration": 3501,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "a0d40298-a834-4904-8838-db29424e28f8",
      "title": "",
      "fullFile": "cypress/integration/orders/draftOrders.js",
      "file": "cypress/integration/orders/draftOrders.js",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [],
      "suites": [
        {
          "uuid": "e634a4b2-6f1d-4fda-b8cb-68678b4dfe84",
          "title": "Draft orders",
          "fullFile": "",
          "file": "",
          "beforeHooks": [],
          "afterHooks": [],
          "tests": [
            {
              "title": "should move draft order to orders",
              "fullTitle": "Draft orders should move draft order to orders",
              "timedOut": null,
              "duration": 3461,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": "[\n  \"-- before all hook (failed).png\",\n  {\n    \"title\": \"Failed screenshot\",\n    \"value\": \"screenshots/orders/draftOrders.js/Draft orders -- should move draft order to orders -- before all hook (failed).png\"\n  }\n]",
              "code": "return itCallback(func);",
              "err": {
                "message": "CypressError: `cy.request()` requires a `url`. You did not provide a `url`.\n\nhttps://on.cypress.io/request\n\nBecause this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Draft orders`\n\nAlthough you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail",
                "estack": "CypressError: `cy.request()` requires a `url`. You did not provide a `url`.\n\nhttps://on.cypress.io/request\n\nBecause this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Draft orders`\n\nAlthough you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail\n    at Context.request (http://localhost:9000/__cypress/runner/cypress_runner.js:160140:19)\nFrom Your Spec Code:\n    at Context.eval (http://localhost:9000/__cypress/tests?p=cypress/support/index.js:400:13)",
                "diff": null
              },
              "uuid": "805c246f-e211-458f-b0db-be9efca3522a",
              "parentUUID": "e634a4b2-6f1d-4fda-b8cb-68678b4dfe84",
              "isHook": false,
              "skipped": false
            }
          ],
          "suites": [],
          "passes": [],
          "failures": [
            "805c246f-e211-458f-b0db-be9efca3522a"
          ],
          "pending": [],
          "skipped": [],
          "duration": 3461,
          "root": false,
          "rootEmpty": false,
          "_timeout": 2000
        }
      ],
      "passes": [],
      "failures": [],
      "pending": [],
      "skipped": [],
      "duration": 0,
      "root": true,
      "rootEmpty": true,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": false,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "6.2.2"
    },
    "marge": {
      "options": {
        "id": "default",
        "reportDir": "cypress/results/json",
        "overwrite": false,
        "html": false,
        "json": true
      },
      "version": "5.2.0"
    }
  }
}